// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerizinanPeternakan.Data;

#nullable disable

namespace PerizinanPeternakan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerizinanPeternakan.Models.LivestockDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LivestockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PermitApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermitApplicationId");

                    b.ToTable("LivestockDetails");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.LivestockPermitApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AdminApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ArrivalPort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CurrentApprovalLevel")
                        .HasColumnType("int");

                    b.Property<string>("DeparturePort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DestinationLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FinalApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedDocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("KepalaDinasId")
                        .HasColumnType("int");

                    b.Property<string>("OriginLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifikatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique();

                    b.HasIndex("KepalaDinasId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionDate");

                    b.HasIndex("UserId");

                    b.HasIndex("VerifikatorId");

                    b.ToTable("PermitApplications");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.PermitApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("PermitApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionDate");

                    b.HasIndex("PermitApplicationId");

                    b.HasIndex("UserId");

                    b.ToTable("PermitApprovalHistories");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.PermitDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("PermitApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermitApplicationId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PermitDocuments");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alamat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoTelepon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TanggalDaftar")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alamat = "Kantor DPMPTSP NTB, Jl. Udayana No. 4 Mataram",
                            Email = "kepaladinas@dpmptsp-ntb.go.id",
                            IsActive = true,
                            NamaLengkap = "Hj. Eva Dewiyani, SP",
                            NoTelepon = "081234567890",
                            Password = "$2a$11$BCGyEESCpVMrVerzreURR.3BZ9uitmtMiaoKJU2pslyMH65gh.xZ.",
                            Role = "KepalaDinas",
                            TanggalDaftar = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "kepaladinas"
                        },
                        new
                        {
                            Id = 2,
                            Alamat = "Kantor DPMPTSP NTB, Jl. Udayana No. 4 Mataram",
                            Email = "admin1@dpmptsp-ntb.go.id",
                            IsActive = true,
                            NamaLengkap = "Ahmad Admin, S.Pt",
                            NoTelepon = "081234567891",
                            Password = "$2a$11$roTC0yhCxb.55PJ/PSMz/uFYEQw00YB657Co8cj8d2M0BzqYFexse",
                            Role = "Admin",
                            TanggalDaftar = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 3,
                            Alamat = "Kantor DPMPTSP NTB, Jl. Udayana No. 4 Mataram",
                            Email = "admin2@dpmptsp-ntb.go.id",
                            IsActive = true,
                            NamaLengkap = "Siti Admin, S.Pt",
                            NoTelepon = "081234567893",
                            Password = "$2a$11$dlnS3JhriSvJcFWWOwX9GefAc2Lk3YbsrFk5VLOjYfHEV0oQOBF9m",
                            Role = "Admin",
                            TanggalDaftar = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 4,
                            Alamat = "Kantor DPMPTSP NTB, Jl. Udayana No. 4 Mataram",
                            Email = "verifikator1@dpmptsp-ntb.go.id",
                            IsActive = true,
                            NamaLengkap = "Budi Verifikator, S.Pt, M.Si",
                            NoTelepon = "081234567894",
                            Password = "$2a$11$Di196bGJ3yOV.whx3TkB.eCnmtV03M/9DIWDIuEzGZFCCU0HK9qZq",
                            Role = "Verifikator",
                            TanggalDaftar = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "verifikator1"
                        },
                        new
                        {
                            Id = 5,
                            Alamat = "Kantor DPMPTSP NTB, Jl. Udayana No. 4 Mataram",
                            Email = "verifikator2@dpmptsp-ntb.go.id",
                            IsActive = true,
                            NamaLengkap = "Rina Verifikator, S.Pt",
                            NoTelepon = "081234567895",
                            Password = "$2a$11$ShNRaNjMF/IxhcOoZGrUuOxI6Pr41tJujx6EuPP5iy.gtenwe.bwi",
                            Role = "Verifikator",
                            TanggalDaftar = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "verifikator2"
                        },
                        new
                        {
                            Id = 6,
                            Alamat = "Desa Suka Maju, Kec. Praya, Lombok Tengah",
                            Email = "user1@example.com",
                            IsActive = true,
                            NamaLengkap = "Budi Peternak",
                            NoTelepon = "081234567896",
                            Password = "$2a$11$n6zBiQ8IgPdOHkghfqQGru2DMtzkqxjOSzUM53teW1UAO73CpmOQO",
                            Role = "User",
                            TanggalDaftar = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "user1"
                        },
                        new
                        {
                            Id = 7,
                            Alamat = "Desa Dena, Kec. Madapangga, Kab. Bima",
                            Email = "cvdena@example.com",
                            IsActive = true,
                            NamaLengkap = "CV. DENA BERSAUDARA",
                            NoTelepon = "081234567897",
                            Password = "$2a$11$Xe5nSUyr88T3rG.Qe/OtD.hzXqtKFW5TQ3U9WYBcCxaOD6x/b3f5a",
                            Role = "User",
                            TanggalDaftar = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "cvdena"
                        },
                        new
                        {
                            Id = 8,
                            Alamat = "Jl. Peternakan No. 15, Mataram",
                            Email = "sarimakmur@example.com",
                            IsActive = true,
                            NamaLengkap = "PT. Sari Makmur Ternak",
                            NoTelepon = "081234567898",
                            Password = "$2a$11$4UyeoBPsfBrqzMEbm25mMuqTLWWigAusH4PuyoSPwi.YRvZYbqCzG",
                            Role = "User",
                            TanggalDaftar = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "sarimakmur"
                        });
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.LivestockDetail", b =>
                {
                    b.HasOne("PerizinanPeternakan.Models.LivestockPermitApplication", "PermitApplication")
                        .WithMany("LivestockDetails")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermitApplication");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.LivestockPermitApplication", b =>
                {
                    b.HasOne("PerizinanPeternakan.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PerizinanPeternakan.Models.User", "KepalaDinas")
                        .WithMany()
                        .HasForeignKey("KepalaDinasId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PerizinanPeternakan.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PerizinanPeternakan.Models.User", "Verifikator")
                        .WithMany()
                        .HasForeignKey("VerifikatorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Admin");

                    b.Navigation("KepalaDinas");

                    b.Navigation("User");

                    b.Navigation("Verifikator");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.PermitApprovalHistory", b =>
                {
                    b.HasOne("PerizinanPeternakan.Models.LivestockPermitApplication", "PermitApplication")
                        .WithMany("ApprovalHistory")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerizinanPeternakan.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PermitApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.PermitDocument", b =>
                {
                    b.HasOne("PerizinanPeternakan.Models.LivestockPermitApplication", "PermitApplication")
                        .WithMany("Documents")
                        .HasForeignKey("PermitApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerizinanPeternakan.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PermitApplication");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("PerizinanPeternakan.Models.LivestockPermitApplication", b =>
                {
                    b.Navigation("ApprovalHistory");

                    b.Navigation("Documents");

                    b.Navigation("LivestockDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
